# Khatib Family Practice - Netlify Configuration File

[build]
  publish = "dist"
  command = """
    echo "==== Starting Build Process ===="
    npm config set loglevel warn
    npm install --no-audit --production=false || exit 1
    echo "==== Base dependencies installed ===="
    npm list chalk clean-css terser glob || true
    echo "==== Installing specific dependency versions ===="
    npm install chalk@4.1.2 clean-css@5.3.3 terser@5.39.0 glob@8.1.0 --no-save || exit 1
    echo "==== All dependencies installed successfully ===="
    echo "==== Starting build script ===="
    node scripts/build.js
  """
  
[build.environment]
  # Updated Node version for compatibility with dependencies
  NODE_VERSION = "18.18.0"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"

# Enable HTTPS and ensure redirect from HTTP to HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Handle PDF forms downloads correctly
[[headers]]
  for = "/forms/*"
    [headers.values]
    Content-Type = "application/pdf"
    Content-Disposition = "attachment"
    Cache-Control = "public, max-age=86400"

# Security headers for all pages
[[headers]]
  for = "/*"
    [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://cdnjs.cloudflare.com https://ajax.googleapis.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://fonts.googleapis.com; img-src 'self' data: https://maps.google.com https://maps.gstatic.com; font-src 'self' https://cdnjs.cloudflare.com https://fonts.gstatic.com; connect-src 'self'; frame-src https://www.google.com https://healow.com; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'"

# Cache static assets
[[headers]]
  for = "/*.css"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
    [headers.values]
    Cache-Control = "public, max-age=604800"

# Enable Forms handling
[build.processing.html]
  pretty_urls = true

# Core plugins - only include essential ones initially
[[plugins]]
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
    baseUrl = "https://khatibfamilypractice.com"
    exclude = ['/thank-you']

# These plugins may be added back once basic build is successful
# [[plugins]]
#   package = "@netlify/plugin-lighthouse"
#   [plugins.inputs]
#     output_path = "reports/lighthouse.html"

# [[plugins]]
#   package = "netlify-plugin-inline-critical-css"

# [[plugins]]
#   package = "netlify-plugin-image-optim"

# [[plugins]]
#   package = "netlify-plugin-no-more-404"
#   [plugins.inputs]
#     on404 = "error"

# Define environment variables
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"
